<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title><?= $this->pageTitle ?></title>
    <base href="<?= $this->getViewFileUrl() ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="*"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <link rel="stylesheet" href="css/fontawesome-all.css" type="text/css" />
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link rel="icon" href="images/favicon.png" type="image/x-icon" />
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
    <link rel="stylesheet" href="https://use.typekit.net/xal1ndu.css">
</head>
<body>
    <main class="page-main">
        <?php require_once $contentTemplate; ?>
    </main>
</body>
</html>
